### ISSUE TITLE
Incorrect code when order >= 3

### ISSUE THREAD

**Issue by mblondel** [geffy/tffm#1]
The code for computing predictions (https://github.com/geffy/tffm/blob/master/tffm.py#L212) is incorrect.

You naively applied Lemma 3.1 from Rendle's original paper (http://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf) but this is incorrect when order >= 3.

If you compare with the predictions obtained by Equation (5) in the paper, you'll see that the predictions are not the same.

**Comment by Bihaqo** [comment]
Thanks for pointing this out, I'm working on a fix and tests to prevent such errors in the future.

**Comment by Bihaqo** [comment]
UPDATE: the test is ready and the dense version of the code should be correct now. The code is still messy though and I'll leave it in the fix_high_order branch for now.

**Comment by geffy** [comment]
Thanks to @mblondel for pointing out the problem and @bihaqo for the solution.
Code #2  still a little bit messy, but seems to be ok and merged to master.
@mblondel, can you check it now?

**Comment by mblondel** [comment]
"t supports arbitrary order of interactions and has linear complexity in in number of features"

I don't think this remark is true.

**Comment by Bihaqo** [comment]
@mblondel And why not? The test should verify the correctness. I believe
the complexity should be linear, and to check it @geffy added a plot of
time vs the number of features into the example Jupiter notebook: it indeed
looks linear.

**Comment by geffy** [comment]
Anyway, the issue about incorrect code is fixed.
If still doubt about complexity -- create new issue, please.
