### ISSUE TITLE
Save / load Model

### ISSUE THREAD

**Issue by LombardiLeandro** [geffy/tffm#25]
Hi, 

I've been using TFFM for prototyping and is great, thank you. It is actually one of my first experiences with TF. 

I found there is no direct save/load for a TFFM model. If there is, ignore this post completely :)

I understand you can save/load underlying TF objects. More precisely, say I have a 
model = TFFMRegressor( ... )
that I want to save and load.

So, my workaround is: 
-> Save: underlying TF objects via: model.core.saver.save(model.session, 'filename')

-> Load: 
1) Create an (almost) identical  model = TFFMRegressor( ..., n_epochs=1 )
2) Train for 1 epoch with model.fit()
3) Retrieving TF graph and Session with
saver = tf.train.import_meta_graph('filename.meta')
saver.restore(model.session, tf.train.latest_checkpoint('./'))

First of all, since I am not very experienced in TF, I do not know if this is even enough / correct.

Then, I would like to suggest a .save() and .load() method for TFFM models.

**Comment by geffy** [comment]
Hi,
there is a already implemented way to save model very similar to what you described: https://github.com/geffy/tffm/blob/master/tffm/base.py#L251-L258

You can also find usage example in `example.ipynb`

**Comment by LombardiLeandro** [comment]
Thanks! somehow I didn't realize it was there and how to use it.
