### ISSUE TITLE
Working with various optimizers

### ISSUE THREAD

**Issue by mhajabri** [geffy/tffm#27]
Hello, 

I've tried the implementation using ADAM optimizer and it works out pretty good. I wanted to compare the results I got with AdaDelta or FTRL but the algorithm always returns a 0% recall with the 'predictions' vector containing only negative samples.

Is anyone else experiencing this issue ? 

Thanks

**Comment by geffy** [comment]
Hi,
seems like model doesn't converge in your case. 
Did you try to decrease learning rate and\or init_std?

**Comment by geffy** [comment]
Close this thread, feel free to reopen if needed
