### ISSUE TITLE
If log dir setting to ".", it just cleans all the files without any warning

### ISSUE THREAD

**Issue by Vimos** [geffy/tffm#4]
Hi, log_dir parameter is doing something dangerous. The first try of this code, I set log dir to ".", and without any warning, it just removed all my files of that dir. 

I hope this can be fixed, so that no such thing happens to anybody else.

**Comment by geffy** [comment]
Yes, you are right, it's kind of dangerous.
Removed this part in https://github.com/geffy/tffm/commit/cc9f06acdeb70370dd74d28dbf1600372795fbba
Now it just creates new log file for every model -- you should manage it manually or/and use relative/wall horizontal axis in TensorBoard
